# Generated by Django 6.1 on 2026-08-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="oauthstate",
            name="invite_token",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
