# Generated by Django 6.1 on 2026-08-31 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("failed", "Action failed"),
                            ("done", "Action finished"),
                            ("info", "Information"),
                        ],
                        default="failed",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=512)),
                ("body", models.TextField(blank=True, default="")),
                (
                    "target_url",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "retry_method",
                    models.CharField(blank=True, default="", max_length=8),
                ),
                (
                    "retry_path",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("retry_body", models.JSONField(blank=True, null=True)),
                (
                    "dedupe_key",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("attempts", models.PositiveIntegerField(default=1)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "read_at"],
                        name="notificatio_user_id_47e85c_idx",
                    ),
                    models.Index(
                        fields=["user", "dedupe_key"],
                        name="notificatio_user_id_4f70d5_idx",
                    ),
                ],
            },
        ),
    ]
