# Generated by Django 6.1 on 2026-08-26 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("active", "Active"),
                            ("on_hold", "On hold"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="planning",
                        max_length=16,
                    ),
                ),
                ("started_on", models.DateField(blank=True, null=True)),
                ("target_end_on", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GitLabRepo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gitlab_project_id",
                    models.BigIntegerField(db_index=True, unique=True),
                ),
                ("path_with_namespace", models.CharField(max_length=512)),
                ("name", models.CharField(max_length=255)),
                ("web_url", models.URLField(blank=True)),
                ("http_url_to_repo", models.CharField(blank=True, max_length=512)),
                ("ssh_url_to_repo", models.CharField(blank=True, max_length=512)),
                ("default_branch", models.CharField(default="main", max_length=255)),
                ("visibility", models.CharField(default="private", max_length=32)),
                ("namespace_path", models.CharField(blank=True, max_length=512)),
                ("documentation_branch_ready", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repo",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "GitLab repository",
                "verbose_name_plural": "GitLab repositories",
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("brd", "Business requirements document"),
                            ("technical", "Technical document"),
                        ],
                        max_length=32,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("repo_path", models.CharField(max_length=512)),
                ("content_type", models.CharField(blank=True, max_length=128)),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                ("content_hash", models.CharField(blank=True, max_length=64)),
                ("commit_sha", models.CharField(blank=True, max_length=64)),
                ("uploaded_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["project", "kind"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "kind"), name="uniq_document_per_kind"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("branch_name", models.CharField(blank=True, max_length=512)),
                ("access_level", models.PositiveSmallIntegerField(default=30)),
                ("synced_to_gitlab", models.BooleanField(default=False)),
                ("sync_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__first_name", "user__username"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "user"), name="uniq_project_member"
                    )
                ],
            },
        ),
    ]
