# Generated by Django 6.1 on 2026-08-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gitlabrepo",
            name="created_by_app",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="gitlabrepo",
            name="documentation_branch",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
