# Generated by Django 6.1 on 2026-08-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="milestone",
            name="is_inherited",
            field=models.BooleanField(default=False),
        ),
    ]
