# Generated by Django 6.1 on 2026-08-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0002_milestone_is_inherited"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="work_item_type",
            field=models.CharField(blank=True, default="task", max_length=32),
        ),
    ]
