# Generated by Django 6.1 on 2026-08-31 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0003_task_work_item_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=512)),
                ("description", models.TextField(blank=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=16,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("opened", "Open"), ("closed", "Resolved")],
                        default="opened",
                        max_length=16,
                    ),
                ),
                (
                    "gitlab_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "gitlab_iid",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                ("web_url", models.URLField(blank=True)),
                ("is_linked", models.BooleanField(default=False)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="planning.task",
                    ),
                ),
            ],
            options={
                "ordering": ["state", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["task", "state"], name="planning_is_task_id_f32f69_idx"
                    ),
                    models.Index(
                        fields=["assignee", "state"],
                        name="planning_is_assigne_1d80df_idx",
                    ),
                ],
            },
        ),
    ]
