"""Let an issue hang off a todo, not only a task.

Plenty of work is a line somebody wrote on their own day that was never part of
any milestone. Refusing to record a problem with it — because the thing it
concerns is not in the plan — is how a defect ends up in a message to somebody
instead of in the system.

``raised_against`` is added here and backfilled: every issue that already exists
points at a task, so that task's title is the snapshot. ``0006`` then forbids it
being empty, and would fail on those rows without this.

The ordering is deliberate. Columns are added, *then* rows are updated — never
the other way round, and the constraint is a separate migration rather than an
``ALTER`` following DML in the same transaction. See ``daily/0003`` for what
that costs when it is got wrong.
"""

# Generated by Django 6.1 on 2026-08-31 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def snapshot_existing(apps, schema_editor):
    """Say what each issue that already exists was raised against."""
    Issue = apps.get_model("planning", "Issue")
    for pk, title, task_title in Issue.objects.filter(raised_against="").values_list(
        "pk", "title", "task__title"
    ):
        Issue.objects.filter(pk=pk).update(raised_against=(task_title or title)[:512])


class Migration(migrations.Migration):

    dependencies = [
        ("daily", "0004_drop_todo_claim"),
        ("planning", "0004_add_issue"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="raised_against",
            field=models.CharField(default="", max_length=512),
        ),
        migrations.AddField(
            model_name="issue",
            name="todo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issues",
                to="daily.todo",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issues",
                to="planning.task",
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["todo", "state"], name="planning_is_todo_id_90efea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["reported_by", "state"], name="planning_is_reporte_410653_idx"
            ),
        ),
        migrations.RunPython(snapshot_existing, migrations.RunPython.noop),
    ]
