# Generated by Django 6.1 on 2026-08-29 09:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_teaminvite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={"ordering": ["is_general", "name"]},
        ),
        migrations.AddField(
            model_name="team",
            name="is_general",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_general", True)),
                fields=("owner",),
                name="uniq_general_team_per_owner",
            ),
        ),
    ]
