# Generated by Django 6.1 on 2026-08-31 11:02

"""Collapse the two-stage tick back to one.

A member's tick used to only *claim* a line — "I have finished this" — and an
owner had to close it in the morning meeting. Two problems with it in practice:
ticking your own work felt like filing a request, and reopening a closed line
cleared ``done_at`` but left ``claimed_at`` behind, so it came back reading
"marked done by … · waiting to be closed" instead of open.

Dropping the columns loses who first said a line was finished. That is a real
loss and it is deliberate: ``closed_by`` records who ticked it, which is the
same person in every case that mattered.

Anything sitting in the claimed state when this runs — claimed but not closed —
would become plain open on the way through, which is wrong: the person did tick
it. So the forward step closes those first, crediting the claimer.
"""

from django.db import migrations, models


def close_what_was_claimed(apps, schema_editor):
    """A line somebody ticked stays ticked."""
    Todo = apps.get_model("daily", "Todo")
    Todo.objects.filter(done_at__isnull=True, claimed_at__isnull=False).update(
        done_at=models.F("claimed_at"), closed_by=models.F("claimed_by")
    )


class Migration(migrations.Migration):

    dependencies = [
        ("daily", "0002_todo_claimed_at_todo_claimed_by_todo_closed_by"),
    ]

    operations = [
        migrations.RunPython(close_what_was_claimed, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="todo",
            name="claimed_at",
        ),
        migrations.RemoveField(
            model_name="todo",
            name="claimed_by",
        ),
    ]
